# Authentication.
exec-once = systemctl --user start hyprpolkitagent
#exec-once = kwalletd6

# Use wlsunset for less blue light at night.
exec-once = wlsunset -l 51.5 -L 6.98 -T 6500 -t 3500

# Wallpapers
exec-once = hyprpaper

# System bar
exec-once = waybar
