$font = EB Garamond

animations {
	enabled = true
	bezier = linear, 1, 1, 0, 0
	animation = fadeIn, 1, 3, linear
	animation = fadeOut, 1, 3, linear
	animation = inputFieldDots, 1, 1.2, linear
}

background {
	color = rgb(000000)
}

input-field {
	size = 500, 90
	outline_thickness = 0
	inner_color = rgb(000000)
	outer_color = rgb(000000)

	font_color = rgb(ffffff)
	font_family = $font

	check_color = rgb(000000)
	placeholder_text =

	fade_on_empty = false

	fail_color = rgb(000000)
	fail_text =

	dots_text_format = ×
	dots_size = 0.5
	dots_spacing = 0.25

	halign = center
	valign = center
}

# TIME
label {
	monitor =
	text = <span font_features="+onum">$TIME</span>
	font_size = 60
	font_family = $font

	position = 0, 130
	halign = center
	valign = center
}

# DATE
label {
	monitor =
	text = cmd[update:60000] echo "<span font_features='+onum'>$(date +'%A, %d %B %Y')</span>"
	font_size = 40
	font_family = $font

	position = 0, -120
	halign = center
	valign = center
}
