# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
	preserve_split = true
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
	new_status = master
}


